services:
    db:
      image: postgres:latest
      mem_limit: 256m
      cpus: 0.5
      volumes: 
        - postgresql_bin:/usr/lib/postgresql
        - postgres_data:/var/lib/postgresql/data
        - ./files:/files
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports: 
        - "5433:5432"
      networks:
        - gbnetwork

    # pgadmin:
    #   container_name: pgadmin
    #   image: dpage/pgadmin4
    #   mem_limit: 256m
    #   cpus: 0.5
    #   environment: 
    #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
    #     PGADMIN_LISTEN_PORT: 5050
    #     PGADMIN_CONFIG_SERVER_MODE: 'False'
    #   volumes:
    #     - postgresql_bin:/usr/lib/postgresql
    #     - pgadmin_root_prefs:/root/.pgadmin
    #     - pgadmin_working_dir:/var/lib/pgadmin
    #     - ./files:/files
    #   ports:
    #     - 5050:5050
    #   networks:
    #     - gbnetwork
    api:
      build: 
        context: .
        dockerfile: Dockerfile
      mem_limit: 256m
      cpus: 0.5      
      volumes: 
        - ./:/app
      environment:
        DATABASE_URL: ${DATABASE_URL}
      ports:
        - "8050:8000"
      depends_on: 
        - db
      networks:
        - gbnetwork
networks:
  gbnetwork:
    driver: bridge
volumes:
  postgres_data:    
    driver: local
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_bin:
    driver: local