services:
    db:
      image: postgres:latest
      volumes: 
        - postgresql_bin:/usr/lib/postgresql
        - postgres_data:/var/lib/postgresql/data
        - ./files:/files
      environment:
        POSTGRES_DB: api_nbs_gb
        POSTGRES_USER: gb_user
        POSTGRES_PASSWORD: 7iVLJ9ch6YU
      ports: 
        - "5433:5432"
      networks:
        - gbnetwork

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment: 
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: 7iVLJ9ch6YU
        PGADMIN_LISTEN_PORT: 5050
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - postgresql_bin:/usr/lib/postgresql
        - pgadmin_root_prefs:/root/.pgadmin
        - pgadmin_working_dir:/var/lib/pgadmin
        - ./files:/files
      ports:
        - 5050:5050
      networks:
        - gbnetwork
    api:
      build: 
        context: .
        dockerfile: Dockerfile
      volumes: 
        - ./:/app
      environment:
        DATABASE_URL: postgresql://gb_user:7iVLJ9ch6YU@postgres/api_nbs_gb
      ports:
        - "8000:8000"
      depends_on: 
        - db
      networks:
        - gbnetwork
networks:
  gbnetwork:
    driver: bridge
volumes:
  postgres_data:    
    driver: local
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_bin:
    driver: local